# Makefile.os2 -- Anagramarama for ArcaOS/OS2, GCC 9.2/kLIBC + SDL2

CC      = gcc
CFLAGS  = -O2 -Wall -Wno-unused-variable \
          -I. -I/@unixroot/usr/include -I/@unixroot/usr/include/SDL2 \
          -DIS_OS2_HOST

LDFLAGS = -Zomf -Zhigh-mem -Zmap

LIBS    = /@unixroot/usr/lib/SDL2_dll.a \
          /@unixroot/usr/lib/SDL2_image_dll.a \
          /@unixroot/usr/lib/SDL2_mixer_dll.a

TARGET  = ../anagramarama.exe

SRCS = \
    ag.c \
    ag_core.c \
    dlb.c \
    linked.c \
    sdlscale.c \
    sprite.c

OBJS = $(SRCS:.c=.obj)

all: $(TARGET)

$(TARGET): $(OBJS) anagramarama.def
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS) anagramarama.def

%.obj: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	-rm -f *.obj *.d
	-rm -f $(TARGET) anagramarama.map

.PHONY: all clean
